server:
    address: 0.0.0.0
    port: 8888
spring:
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml
    resources:
        add-mappings: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc

server.servlet.session.cookie.name: SESSION_ID

logging:
    file: ./log.log

management:
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: "*"
