server:
    address: 0.0.0.0
    port: 8888
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: vgu
        url: jdbc:postgresql://10.25.128.104/vgu
        username: vgu
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    liquibase:
        enabled: true
        change-log: classpath:db/changelog/db.changelog-master.yaml

    resources:
        add-mappings: false
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 10MB
            max-request-size: 10MB
    session:
        jdbc:
            initialize-schema: always
        store-type: jdbc
